from sqlalchemy import create_engine, text
import os

DATABASE_URL = os.getenv("DATABASE_URL")

engine = create_engine(DATABASE_URL)

sql = """
ALTER TABLE notes ADD COLUMN IF NOT EXISTS file_path VARCHAR(600) DEFAULT '';

ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_character VARCHAR(80) DEFAULT 'robot';
ALTER TABLE users ADD COLUMN IF NOT EXISTS profile_image_url VARCHAR(600) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS biometric_enabled BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS preferred_style VARCHAR(80) DEFAULT 'simple';
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_course VARCHAR(160) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_date VARCHAR(50) DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS target_score INTEGER DEFAULT 80;
ALTER TABLE users ADD COLUMN IF NOT EXISTS xp INTEGER DEFAULT 0;
ALTER TABLE users ADD COLUMN IF NOT EXISTS level INTEGER DEFAULT 1;
ALTER TABLE users ADD COLUMN IF NOT EXISTS streak_days INTEGER DEFAULT 0;

ALTER TABLE notes ADD COLUMN IF NOT EXISTS topics JSONB DEFAULT '[]';
ALTER TABLE notes ADD COLUMN IF NOT EXISTS summary TEXT DEFAULT '';

ALTER TABLE study_memory ADD COLUMN IF NOT EXISTS strong_topics JSONB DEFAULT '[]';
ALTER TABLE study_memory ADD COLUMN IF NOT EXISTS repeated_mistakes JSONB DEFAULT '[]';
ALTER TABLE study_memory ADD COLUMN IF NOT EXISTS preferred_style VARCHAR(80) DEFAULT 'simple';
ALTER TABLE study_memory ADD COLUMN IF NOT EXISTS burnout_risk FLOAT DEFAULT 0;
ALTER TABLE study_memory ADD COLUMN IF NOT EXISTS ai_notes TEXT DEFAULT '';
"""

with engine.begin() as conn:
    conn.execute(text(sql))

print("DATABASE FIXED")